### ISSUE TITLE
cannot use defined values in new values 

### ISSUE THREAD

**Issue by tretmans** [TorXakis/TorXakis#769]
TXS >> val x=42
TXS >>  x = 42
TXS >> val y=x+7
TXS >>  Error {_errorType = Undefined Entity, _errorLoc = ErrorLoc {errorLine = 1, errorColumn = 3}, _errorMsg = "Could not find key \"x\" of type Text when looking for a value of type Proxy * [Loc FuncDeclE]"}

I would like to use x in new val-definition.

**Comment by ramon-janssen** [comment]
This also occurs in LET-expressions in models:

`Stimulus ?x [[ LET y = x IN True NI ]] >-> Response`

gives a parse error

`TXS >>  Errors [Error {_errorType = Undefined Entity, _errorLoc = NoErrorLoc, _errorMsg = "Could not find key Loc {line = 15, start = 19, locUid = 1009} of type Loc VarDeclE when looking for a value of type Proxy * SortId"}]`

(obviously, this example is stupid, but non-stupid occurrences exist)

**Comment by pjljvandelaar** [comment]
@dnadales any idea what goes wrong?
I tried, yet failed so far ;-(

In this example, I couldn't localize where the variable (in this example `y`) is replaced/ substitute / simplified by its expression (in this example `x`) in the expression (in this example `True`).
Yet, I saw that let var declarations are combined, in a way that violates contexts.

See Parser/Data.hs
```
-- | Extract all the let-variable declarations of an expression.
--
expLetVarDecls :: ExpDecl -> [[LetVarDecl]]
expLetVarDecls ParseTree { child = VarRef _ _  } = []
expLetVarDecls ParseTree { child = ConstLit _  } = []
expLetVarDecls ParseTree { child = LetExp vs e }
    =  (toList <$> vs)
    ++ expLetVarDecls e
    ++ concatMap (concatMap (expLetVarDecls . varDeclExp)) (toList <$> vs)
expLetVarDecls ParseTree { child = If e0 e1 e2 } =
    expLetVarDecls e0 ++ expLetVarDecls e1 ++ expLetVarDecls e2
expLetVarDecls ParseTree { child = Fappl _ _ exs } =
    concatMap expLetVarDecls exs
```
I hope that the local variables are map to globally unique variables....

**Comment by dnadales** [comment]
The function above simply collects all the `LetVarDecl`'s. In the example above `x` is not a let variable declaration, so it won't be part of the result.

**Comment by pjljvandelaar** [comment]
I agree that 'x' is not, yet 
'y' is a Let variable declaration I assume.

**Comment by dnadales** [comment]
I see, you're looking for `y`. As far as I remember the `LET` expression of the example is not a `ExpDecl` but a behavior expression declaration ...

**Comment by dnadales** [comment]
I think I fixed it, but @ramon-janssen  and @pjljvandelaar please review.

**Comment by pjljvandelaar** [comment]
@dnadales great!

**Comment by pjljvandelaar** [comment]
The bug reported by Jan is still present:
```
PS C:\TorXakis.git> torxakis
TXS >>  TorXakis :: Model-Based Testing
TXS >>  txsserver starting: "PC-17716.tsn.tno.nl" : 53381
TXS >>  Solver "z3" initialized : Z3 [4.7.1]
TXS >>  TxsCore initialized
TXS >>  input files parsed:
TXS >> val x =42
TXS >>  x = 42
TXS >> val y = x + 7
TXS >>  Error {_errorType = Undefined Entity, _errorLoc = ErrorLoc {errorLine = 1, errorColumn = 5}, _errorMsg = "Could not find key \"x\" of type Text when looking for a value of type Proxy * [Loc FuncDeclE]"}
TXS >>  CallStack (from HasCallStack):
TXS >>  error, called at src\TorXakis\Compiler.hs:174:25 in txs-compiler-0.1.0.0-2Ojo4KRwLL3Be0ZIQBGok7:TorXakis.Compiler
TXS >>
```
However, the second issue seems solved: 
[bug.txt](https://github.com/TorXakis/TorXakis/files/2301330/bug.txt)
with content
```
PROCDEF p [Stimulus, Response :: Int] () ::=
    Stimulus ?x [[ LET pos = (x > 0) IN pos NI ]] >-> Response ! x >-> p [ Stimulus, Response ] ()
ENDDEF

CHANDEF Channels ::=
    Stimulus, Response :: Int
ENDDEF

MODELDEF Model ::=
    CHAN IN    Stimulus
    CHAN OUT   Response
    BEHAVIOUR  p [ Stimulus, Response ] ( )
ENDDEF
```

yields
```
PS C:\TorXakis.git> torxakis .\bug.txt

TXS >>  TorXakis :: Model-Based Testing

TXS >>  txsserver starting: "PC-17716.tsn.tno.nl" : 53433
TXS >>  Solver "z3" initialized : Z3 [4.7.1]
TXS >>  TxsCore initialized
TXS >>  input files parsed:
TXS >>  .\bug.txs
TXS >> stepper Model
TXS >>  Stepper started
TXS >> step 4
TXS >>  .....1: Act { { ( Stimulus, [ 63 ] ) } }
TXS >>  .....2: Act { { ( Response, [ 63 ] ) } }
TXS >>  .....3: Act { { ( Stimulus, [ 82 ] ) } }
TXS >>  .....4: Act { { ( Response, [ 82 ] ) } }

TXS >>  PASS
TXS >>
```

**Comment by dnadales** [comment]
Yes indeed. The PR I made only solves the bug that Ramon submitted. 

Regarding this issue, wasn't this behavior the same with the old parser?

**Comment by pjljvandelaar** [comment]
V0.6:

C:\Users\tretmansgj\OneDrive - TNO\MyData\TorXakis\BugExperiments\AlanRibeiro>torxakis

TXS >>  TorXakis :: Model-Based Testing

TXS >>  txsserver starting: "PC-31093.tsn.tno.nl" : 55634
TXS >>  Solver "z3" initialized : Z3 [4.6.0]
TXS >>  TxsCore initialized
TXS >>  input files parsed:
TXS >> var x :: Int
TXS >>  [ x ]
TXS >> solve x>10
TXS >>  sat
TXS >>  fromList [(VarId {name = "x", unid = 1004, varsort = SortId {name = "Int", unid = 102}},Cint {cInt = 11})]
TXS >> info
TXS >>  TorXakis version : 0.6.0 (commit: 6f02370)
TXS >>  Build time : Thu 04/05/2018 9:05:20.97
TXS >>



Huidige develop:

$ torxakis

TXS >>  TorXakis :: Model-Based Testing

TXS >>  txsserver starting: "PC-31093.tsn.tno.nl" : 55625
TXS >>  Solver "z3" initialized : Z3 [4.6.0]
TXS >>  TxsCore initialized
TXS >>  input files parsed:
TXS >> var x :: Int
TXS >>  [ x ]
TXS >> solve x>10
TXS >>  Error {_errorType = Undefined Entity, _errorLoc = ErrorLoc {errorLine = 1, errorColumn = 1}, _errorMsg = "Could not find key \"x\" of type Text when looking for a value of type Proxy * [Loc FuncDeclE]"}
TXS >>  CallStack (from HasCallStack):
TXS >>  error, called at src\TorXakis\Compiler.hs:174:25 in txs-compiler-0.1.0.0-71riZrtGetCYjOGtbMxYS:TorXakis.Compiler
TXS >> info
TXS >>  TorXakis version : UNVERSIONED
TXS >>  Build time : Mon 06/12/2017 10:01:59.98
TXS >>
